const ADD_TODO = 'ADD_TODO';
const DELETE_TODO = 'DELETE_TODO';
const EDIT_TODO = 'EDIT_TODO';
const COMPLETE_TODO = 'COMPLETE_TODO';
const COMPLETE_ALL_TODOS = 'COMPLETE_ALL_TODOS';
const CLEAR_COMPLETED = 'CLEAR_COMPLETED';
const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';

export {
  ADD_TODO,
  DELETE_TODO,
  EDIT_TODO,
  COMPLETE_TODO,
  COMPLETE_ALL_TODOS,
  CLEAR_COMPLETED,
  SET_VISIBILITY_FILTER,
};
